### ISSUE TITLE
compile options

### ISSUE THREAD

**Issue by StefanSalewski** [TinBryn/business_card_ray_tracer#1]
How did you compile?

As you used many vector operations like + or * you should ensure that these procs are inlined.

Simplest way is to compile with LTO. Or mark that procs with inline pragma.

And of course compile not in debug mode for speed testing, but I think you did. Maybe try also the new ARC.

For compiler options see tutorials or language manual, I also listed a few options in

http://ssalewski.de/nimprogramming.html#_launching_the_compiler_and_running_the_program

**Comment by StefanSalewski** [comment]
No, running time is 4min 30 sec with and without LTO, so inlining seems to work fine. Well I don't know the running time of the original C program...

**Comment by TinBryn** [comment]
There is a top level ``nim.cfg`` file that has the compilation options, so just use ``nim c src/main.nim`` and it should be all good.
